### ISSUE TITLE
Nested walking

### ISSUE THREAD

**Issue by kennethlarsen** [kennethlarsen/lannister#11]
Lannister should be able to check all JS files of sub folders in the root folder provided in `lannister dir/`

**Comment by madsobel** [comment]
Maybe it would be an idea to use a glob library such as [globby](https://www.npmjs.com/package/globby) to fetch files. This would keep the walking code more clean and make functions such as `removeUnwantedFiles` unnecessary.

**Comment by kennethlarsen** [comment]
Yeah I think that's a good idea. Generally the file handling needs improvement. Globby looks great!
