### ISSUE TITLE
Bug when a function with no params are found

### ISSUE THREAD

**Issue by madsobel** [kennethlarsen/lannister#21]
Shit hits the fan when a line like below is found

`
function someFunc() {
  // TODO: Figure out what to do about the dragons
}
`

**Comment by madsobel** [comment]
Also it does not seem to work quite right with anonymous functions or arrow functions.

**Comment by kennethlarsen** [comment]
Yeah that seems pretty bad. I guess we should provide a patch release with a fix for this.
